### ISSUE TITLE
Crash when calling SchedulerStoreSvc.GetClientVersion() in some scenarios

### ISSUE THREAD

**Issue by JDA88** [Azure/hpcpack#50]
#### Problem Description

In some scenarios, for example when publishing as `SelfContained` a call to `StoreServer.RegisterWithServer()` can throw an exception:

```
 ---> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Microsoft.Hpc.Scheduler.Store.SchedulerStoreSvc.GetClientVersion()
   at Microsoft.Hpc.Scheduler.Store.SchedulerStoreSvc..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Hpc.Scheduler.Store.SchedulerStoreSvc.get_ClientVersion()
   at Microsoft.Hpc.Scheduler.Store.StoreServer.RegisterWithServer()
   at Microsoft.Hpc.Scheduler.Store.StoreServer.RegisterEvent(String schedulerNode)
   at Microsoft.Hpc.Scheduler.Store.StoreServer.ConnectWcfAsync(CancellationToken token)
   at Microsoft.Hpc.Scheduler.Store.StoreServer.InternalConnectAsync(CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Store.StoreServer.ConnectAsync(StoreConnectionContext context, CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Store.SchedulerStoreSvc.InitializeAsync(CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Store.SchedulerStoreSvc.RemoteConnectAsync(StoreConnectionContext context, CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Store.SchedulerStore.ConnectAsync(StoreConnectionContext context, CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Scheduler.ConnectAsync(SchedulerConnectionContext context, CancellationToken token, ConnectMethod method)
```

The problem is that `SchedulerStoreSvc.GetClientVersion()` call `Assembly.GetExecutingAssembly().Location` that can return an empty string.

It can easily be fixed using a different approach:

```csharp
//Crash because [.Location] is an empty string
var versionInfo = FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location);

//Works even when published as SelfContained
var versionInfo  = Assembly.GetExecutingAssembly().GetName().Version;
```

#### Steps to Reproduce
Publish an application as `SelfContained` and try to connet to any server.

#### Expected Results
Connection successfull

#### Actual Results
Crash

**Comment by YutongSun** [comment]
Thanks. We will fix that.
