### ISSUE TITLE
Connect to HPC Pack 2012 R2 server from .NET 6 client

### ISSUE THREAD

**Issue by Nikita-T86** [Azure/hpcpack#51]
Hello,

I'm trying to use Microsoft.HPC.SDK 6.3.8187-beta in my .NET 6.0 application to connect to Server 2012 R2 headnode with HPC Pack 2012 R2 installed. Is it possible? I have an exception below, as I understand, client tries to connect to https://<myheadnode>/HpcNaming//api/fabric/resolve/singleton/SchedulerStatefulService, but on headnode there is no such endpoint. I'd expect that client should use TCP instead of HTTP as in old HPC Pack 2012 SDK, is it possible to switch protocol to connect to old servers?

 [GetCertificateValidationCallback] Ignore all certificate validation error.
 [GetCertificateValidationCallback] Ignore all certificate validation error.
 [HpcFabricRestContext] Calling HpcNaming//api/fabric/resolve/singleton/SchedulerStatefulService on <myheadnode>:443.
 cert issuer CN=......., sslPolicyErrors RemoteCertificateNameMismatch
 [RetryManager] System.Net.Http.HttpRequestException:Response status code does not indicate success: 404 (Not Found). RetryCount: 0 
 Caller: GetHttpApiCallAsync in C:\__w\1\s\src\HpcCommon\HpcContext\Extensions\HttpClientExtension.cs:line 21
 [RetryManager] System.Net.Http.HttpRequestException:Response status code does not indicate success: 404 (Not Found). RetryCount: 1 
 Caller: GetHttpApiCallAsync in C:\__w\1\s\src\HpcCommon\HpcContext\Extensions\HttpClientExtension.cs:line 21
 [RetryManager] System.Net.Http.HttpRequestException:Response status code does not indicate success: 404 (Not Found). RetryCount: 2 
 Caller: GetHttpApiCallAsync in C:\__w\1\s\src\HpcCommon\HpcContext\Extensions\HttpClientExtension.cs:line 21
 [RetryManager] Execution failed with 3 retires. 
Caller: GetHttpApiCallAsync in C:\__w\1\s\src\HpcCommon\HpcContext\Extensions\HttpClientExtension.cs:line 21 Exception:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Hpc.HttpClientExtension.<>c__DisplayClass5_0.<<GetHttpApiCallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Hpc.RetryManager.InvokeWithRetryAsync[T](Func`1 function, Func`2 exPredicate, CancellationToken cancellationToken, String menberName, String sourceFilePath, Int32 sourceLineNumber)
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Hpc.HttpClientExtension.<>c__DisplayClass5_0.<<GetHttpApiCallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Hpc.RetryManager.InvokeWithRetryAsync[T](Func`1 function, Func`2 exPredicate, CancellationToken cancellationToken, String menberName, String sourceFilePath, Int32 sourceLineNumber)
   at Microsoft.Hpc.RetryManager.InvokeWithRetryAsync[T](Func`1 function, Func`2 exPredicate, CancellationToken cancellationToken, String menberName, String sourceFilePath, Int32 sourceLineNumber)
   at Microsoft.Hpc.HttpClientExtension.GetHttpApiCallAsync(HttpClient httpClient, String endpoint, String apiRoute, CancellationToken cancellationToken, Func`2 exPredicate, Boolean ensureSuccessStatusCode)
   at Microsoft.Hpc.HpcFabricRestContext.<>c__DisplayClass15_0`1.<<GetFirstHttpApiCallResponseAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Hpc.HpcFabricRestContext.GetFirstHttpApiCallResponseAsync[T](CancellationToken cancellationToken, String routeString, String parameter)
   at Microsoft.Hpc.HpcFabricRestContext.ResolveSingletonServicePrimaryAsync(String serviceName, CancellationToken token)
   at Microsoft.Hpc.ServiceResolverExtension.ResolveSchedulerNodeAsync(IHpcContext context)
   at Microsoft.Hpc.Scheduler.Store.StoreConnectionContext.ResolveSchedulerNodeAsync(CancellationToken token)
   at Microsoft.Hpc.Scheduler.Store.StoreServer.ConnectWcfAsync(CancellationToken token)
   at Microsoft.Hpc.Scheduler.Store.StoreServer.InternalConnectAsync(CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Store.StoreServer.ConnectAsync(StoreConnectionContext context, CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Store.SchedulerStoreSvc.InitializeAsync(CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Store.SchedulerStoreSvc.RemoteConnectAsync(StoreConnectionContext context, CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Store.SchedulerStore.ConnectAsync(StoreConnectionContext context, CancellationToken token, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Scheduler.ConnectAsync(SchedulerConnectionContext context, CancellationToken token, ConnectMethod method)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Hpc.Scheduler.Scheduler.Connect(String cluster, ConnectMethod method)
   at Microsoft.Hpc.Scheduler.Scheduler.Connect(String cluster)

**Comment by YutongSun** [comment]
This is not possible because HPC Pack 2012 R2 is using .Net Remoting which has been deprecated since .Net 5. You may only try  .Net Framework version of SDK to connect to HPC Pack 2012 R2 clusters. Also note, HPC Pack 2012 R2 is end of support since April 11, 2023. Please consider migrating the cluster to the latest HPC Pack 2019 Update 2.
